### ISSUE TITLE
Log In and Sign Up Forms Conflicting

### ISSUE THREAD

**Issue by Bhearre** [cferg019/CGK#23]
Casey and Kali,

The Sign Up and Login buttons give the appearance that they are leading to the same Log In Modal Page.  When working with Bryan he indicated that the content was different but that the forms were in the same space so one was overwriting the other.  He further indicated that he thought this could be fixed via CSS so that the modals don't pop up in the same space.

**Comment by cferg019** [comment]
Fixed with recent Pull Request.
